### ISSUE TITLE
"Your login might be tampered with."

### ISSUE THREAD

**Issue by ALNSBroadside** [wpo365/wpo365-login#12]
Hi there,

I'm having a similar issue to #9 in that when I try to go to /wp-admin, it takes me to the MS login as expected, but then after I login it takes me to the wp-login.php with the error "Your login might be tampered with. Please contact your System Administrator."

This is from my error_log:
[17-Oct-2017 13:23:26 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[17-Oct-2017 13:23:26 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[17-Oct-2017 13:23:27 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[17-Oct-2017 13:23:27 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[17-Oct-2017 13:23:37 UTC] DEBUG (7.1.7): Processing incoming OpenID Connect id_token
[17-Oct-2017 13:23:37 UTC] DEBUG (7.1.7): Processing an new id token
[17-Oct-2017 13:23:37 UTC] DEBUG (7.1.7): Getting current public keys from MSFT
[17-Oct-2017 13:23:38 UTC] DEBUG (7.1.7): Cookie WPO365_LOGIN_ERR_MSGS with value [value removed for privacy] set for  in [address removed for privacy] (https://[address removed for privacy])
[17-Oct-2017 13:23:38 UTC] ERROR (7.1.7): id token could not be processed and user will be redirected to default Wordpress login
[17-Oct-2017 13:23:38 UTC] DEBUG (7.1.7): Destroying session index.php
[17-Oct-2017 13:23:38 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in [address removed for privacy] (https://[address removed for privacy])
[17-Oct-2017 13:23:38 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[17-Oct-2017 13:23:38 UTC] DEBUG (7.1.7): Cancelling session validation for page wp-login.php because selected scenario is 'Internet'
[17-Oct-2017 13:23:38 UTC] DEBUG (7.1.7): Cookie WPO365_LOGIN_ERR_MSGS with value  set for  in [address removed for privacy] (https://[address removed for privacy])

Any ideas what I've done wrong?

Thank you!

**Comment by wpo365** [comment]
Hi

Thanks for reporting this. From the log file I can see that all goes perfectly well up and till the moment the plugin is about to decode the token received from Microsoft. Since this behavior is not reproduced on our test systems it may take me a bit of time but I will try and do some more research into alternative ways of formatting the input just before it will be decoded. 

Thanks for your patience!

**Comment by wpo365** [comment]
Hi @ALNSBroadside 

I've just uploaded an slightly improved version to Wordpress. You should see in your wp-admin that there is an update available. I can't promise it will solve the issue at hand, as I can't tell for sure what's causing. I'm guessing one of the following issues:

1. Algorithm not supported
2. Algorithm name not upper case and hence not recognized
3. Token not properly formatted

I've implemented improvements for 2 and 3 and additional logging to find out if coding is not supported. 

It would be great if you can let me know if this already fixed the problem or else I'd be very interested in log output.

Thanks!

**Comment by ALNSBroadside** [comment]
Thank you for the quick response!  I've just tried it again after updating. It's no longer taking me to the login screen with the error anymore - instead if I try to go to wp-admin (for example), it goes through the whole login procedure, then takes me back to the home page, but not logged in.  It doesn't seem to have created the user either.

This is from the error_log:
[18-Oct-2017 07:52:53 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:52:53 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:52:53 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:52:53 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:54:18 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:54:18 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:54:19 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:54:19 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:54:36 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:54:36 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:54:36 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:54:36 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:54:39 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:54:39 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:54:39 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:54:39 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:55:01 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:55:01 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[18-Oct-2017 07:55:02 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:55:02 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'

It doesn't seem to be doing any of the steps it was doing yesterday for some reason.

**Comment by ALNSBroadside** [comment]
I've just tried it in "intranet mode" and this time it just takes me in a loop around logging in on the MS page.  Logs:

[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Validating session for page index.php
[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Destroying session index.php
[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Session data invalid or incomplete found
[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Cookie WPO365_NONCE with value 59e70963eaa92 set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:23 UTC] DEBUG (7.1.7): Getting fresh id and authorization tokens: https://login.microsoftonline.com/6326d17b-8cd6-4eec-93da-beea9030f29d/oauth2/authorize?client_id=cc57c2d6-d70c-4a8b-9e95-380794deafe8&response_type=id_token+code&redirect_uri=https%3A%2F%2F<site>.co.uk&response_mode=form_post&scope=openid&resource=cc57c2d6-d70c-4a8b-9e95-380794deafe8&state=https%3A%2F%2F<site>.co.uk%2F&nonce=59e70963eaa92
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Validating session for page index.php
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Destroying session index.php
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Session data invalid or incomplete found
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Cookie WPO365_NONCE with value 59e709686050f set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:28 UTC] DEBUG (7.1.7): Getting fresh id and authorization tokens: https://login.microsoftonline.com/6326d17b-8cd6-4eec-93da-beea9030f29d/oauth2/authorize?client_id=cc57c2d6-d70c-4a8b-9e95-380794deafe8&response_type=id_token+code&redirect_uri=https%3A%2F%2F<site>.co.uk&response_mode=form_post&scope=openid&resource=cc57c2d6-d70c-4a8b-9e95-380794deafe8&state=https%3A%2F%2F<site>.co.uk%2F&nonce=59e709686050f
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Validating session for page index.php
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Destroying session index.php
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Session data invalid or incomplete found
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Cookie WPO365_NONCE with value 59e7096c80305 set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:32 UTC] DEBUG (7.1.7): Getting fresh id and authorization tokens: https://login.microsoftonline.com/6326d17b-8cd6-4eec-93da-beea9030f29d/oauth2/authorize?client_id=cc57c2d6-d70c-4a8b-9e95-380794deafe8&response_type=id_token+code&redirect_uri=https%3A%2F%2F<site>.co.uk&response_mode=form_post&scope=openid&resource=cc57c2d6-d70c-4a8b-9e95-380794deafe8&state=https%3A%2F%2F<site>.co.uk%2F&nonce=59e7096c80305
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Validating session for page index.php
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Destroying session index.php
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Session data invalid or incomplete found
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Cookie WPO365_NONCE with value 59e70970d0c94 set for  in <site>.co.uk (https://<site>.co.uk)
[18-Oct-2017 07:57:36 UTC] DEBUG (7.1.7): Getting fresh id and authorization tokens: https://login.microsoftonline.com/6326d17b-8cd6-4eec-93da-beea9030f29d/oauth2/authorize?client_id=cc57c2d6-d70c-4a8b-9e95-380794deafe8&response_type=id_token+code&redirect_uri=https%3A%2F%2F<site>.co.uk&response_mode=form_post&scope=openid&resource=cc57c2d6-d70c-4a8b-9e95-380794deafe8&state=https%3A%2F%2F<site>.co.uk%2F&nonce=59e70970d0c94

**Comment by wpo365** [comment]
Thanks @ALNSBroadside  and basically: This is good news :) I think it may be possible that you missed one configuration step:

Last but not least, grant permissions to the App by clicking Required Permissions on the Settings blade and then Grant Permissions (as an Administrator on behalf of all your users). Failing to do so may result in an error when users try to log on to your intranet.

![image](https://user-images.githubusercontent.com/32041702/31715183-118cd7e4-b403-11e7-877b-6fa8816736d0.png)

This is described ![here](https://www.wpo365.com/how-to-install-wordpress-office-365-login-plugin/) ... And I guess we should improve the code to detect that the message received back from Microsoft is a valid message but a message that contains an error instead of the expected token.

Many Thanks and please let me know whether this was indeed the (last?) missing "step".

**Comment by ALNSBroadside** [comment]
Hmm, I had already done that. Just did it again though to be safe
![capture](https://user-images.githubusercontent.com/32873361/31717982-0c28032a-b406-11e7-8d09-8ce9a0d735fd.PNG)
But still the same thing unfortunately :(

Trying to go to wp-admin in internet mode just does this:
[18-Oct-2017 12:09:10 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 12:09:10 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'

and trying to go to the homepage in intranet mode does this:
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Validating session for page index.php
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Destroying session index.php
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in [sitename].co.uk (https://[sitename].co.uk)
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Session data invalid or incomplete found
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Cookie WPO365_NONCE with value 59e744a421700 set for  in [sitename].co.uk (https://[sitename].co.uk)
[18-Oct-2017 12:10:12 UTC] DEBUG (7.1.7): Getting fresh id and authorization tokens: https://login.microsoftonline.com/6326d17b-8cd6-4eec-93da-beea9030f29d/oauth2/authorize?client_id=cc57c2d6-d70c-4a8b-9e95-380794deafe8&response_type=id_token+code&redirect_uri=https%3A%2F%2F[sitename].co.uk&response_mode=form_post&scope=openid&resource=cc57c2d6-d70c-4a8b-9e95-380794deafe8&state=https%3A%2F%2F[sitename].co.uk%2F&nonce=59e744a421700

I've tried in incognito and with a colleague's account too.

Is there anything else I could do to help get to the bottom of this? Happy to give you a site login or something if it would help!

**Comment by wpo365** [comment]
@ALNSBroadside I have uploaded a new version of the plugin (1.11). This doesn't do anything else, so it won't solve the problem. However, it seems that the login is basically OK and your AD app is registered OK or else the flow would have stopped earlier. However, after login the plugin receives instead of a user id most likely an error message. So far this error wasn't caught and this has now changed. It will also prevent a continuous reloading in such cases. And it will also log the error description in the log file. So if things are coming towards us, we should know what causes this unexpected behavior. Again, many thanks for your time and support on this.

**Comment by ALNSBroadside** [comment]
Ooh, that helped!

The log now gives me:
[18-Oct-2017 13:37:22 UTC] ERROR (7.1.7): AADSTS50105: The signed in user is not assigned to a role for the application \'cc57c2d6-d70c-4a8b-9e95-380794deafe8\'.

The rest of it goes:
Trace ID: 4861b0ac-f55d-4e00-b1d9-5d23bfc6c200
Correlation ID: b7e46104-c80d-4a7d-87f6-7d8fbf4c493f
Timestamp: 2017-10-18 13:37:22Z
[18-Oct-2017 13:37:22 UTC] DEBUG (7.1.7): Cookie WPO365_LOGIN_ERR_MSGS with value YWNjZXNzX2RlbmllZC4gUGxlYXNlIGNvbnRhY3QgeW91ciBTeXN0ZW0gQWRtaW5pc3RyYXRvci4= set for  in [site]co.uk (https://[site].co.uk)

So I guess I need to find out how to assign an application role

**Comment by ALNSBroadside** [comment]
Gah I thought we had it there. In Azure AD I went to Enterprise Applications, found the application and went to properties and it has additional settings, one of which is "User assignment required?" set to yes.
I set it to "No" and saved it.
Tried logging in again and.... it takes me back to the wordpress login screen with "Your login might be tampered with. Please contact your System Administrator."

Log:
[18-Oct-2017 13:50:18 UTC] DEBUG (7.1.7): Processing incoming OpenID Connect id_token
[18-Oct-2017 13:50:18 UTC] DEBUG (7.1.7): Processing an new id token
[18-Oct-2017 13:50:18 UTC] DEBUG (7.1.7): Algorithm found RS256
[18-Oct-2017 13:50:18 UTC] DEBUG (7.1.7): Skipping SSL peer and host verification
[18-Oct-2017 13:50:18 UTC] DEBUG (7.1.7): Getting current public keys from MSFT
[18-Oct-2017 13:50:19 UTC] DEBUG (7.1.7): Cookie WPO365_LOGIN_ERR_MSGS with value WW91ciBsb2dpbiBtaWdodCBiZSB0YW1wZXJlZCB3aXRoLiBQbGVhc2UgY29udGFjdCB5b3VyIFN5c3RlbSBBZG1pbmlzdHJhdG9yLg== set for  in [sitename].co.uk (https://[sitename].co.uk)
[18-Oct-2017 13:50:19 UTC] ERROR (7.1.7): id token could not be processed and user will be redirected to default Wordpress login
[18-Oct-2017 13:50:19 UTC] DEBUG (7.1.7): Destroying session index.php
[18-Oct-2017 13:50:19 UTC] DEBUG (7.1.7): Cookie WPO365_AUTH with value  set for  in [sitename].co.uk (https://[sitename].co.uk)
[18-Oct-2017 13:50:19 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[18-Oct-2017 13:50:19 UTC] DEBUG (7.1.7): Cancelling session validation for page wp-login.php because selected scenario is 'Internet'
[18-Oct-2017 13:50:19 UTC] DEBUG (7.1.7): Cookie WPO365_LOGIN_ERR_MSGS with value  set for  in [sitename].co.uk (https://[sitename].co.uk)

Thank you so much for sticking with this!

**Comment by wpo365** [comment]
@ALNSBroadside I think I know what is causing this (last) hick up: I didn't test with Internet Explorer (or other browsers than Chrome) after I had to change from using session variables to own cookies. And it seems in Internet Explorer (other than in Chrome) that the cookies don't "stick" currently ... I'll be uploading a solution as soon as I have one but possible you could test with Chrome to see whether this makes a different (it should).

**Comment by wpo365** [comment]
@ALNSBroadside I've updated the plugin and published version 1.12 and tested it successfully with IE 11. Hope this will do the trick and also hope you haven't lost hope either! Thanks and look forward to hearing your feedback to this version.

**Comment by ALNSBroadside** [comment]
No hope lost, sticking with it! And thank you for sticking with it too :)

I was using Chrome unfortunately (Version 61.0.3163.100). I'll update and give the new version a go this morning though!

**Comment by ALNSBroadside** [comment]
D'oh, still the "login might be tampered with".

Error log:
[19-Oct-2017 08:33:34 UTC] DEBUG (7.1.7): Processing incoming OpenID Connect id_token
[19-Oct-2017 08:33:34 UTC] DEBUG (7.1.7): Processing an new id token
[19-Oct-2017 08:33:34 UTC] DEBUG (7.1.7): Algorithm found RS256
[19-Oct-2017 08:33:34 UTC] DEBUG (7.1.7): Skipping SSL peer and host verification
[19-Oct-2017 08:33:34 UTC] DEBUG (7.1.7): Getting current public keys from MSFT
[19-Oct-2017 08:33:35 UTC] DEBUG (7.1.7): Setting cookie WPO365_LOGIN_ERR_MSGS with value WW91ciBsb2dpbiBtaWdodCBiZSB0YW1wZXJlZCB3aXRoLiBQbGVhc2UgY29udGFjdCB5b3VyIFN5c3RlbSBBZG1pbmlzdHJhdG9yLg== set for  (https://[sitename].co.uk) OK 
[19-Oct-2017 08:33:35 UTC] ERROR (7.1.7): id token could not be processed and user will be redirected to default Wordpress login
[19-Oct-2017 08:33:35 UTC] DEBUG (7.1.7): Destroying session index.php
[19-Oct-2017 08:33:35 UTC] DEBUG (7.1.7): Setting cookie WPO365_AUTH with value  set for  (https://[sitename].co.uk) OK 
[19-Oct-2017 08:33:35 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[19-Oct-2017 08:33:35 UTC] DEBUG (7.1.7): Cancelling session validation for page wp-login.php because selected scenario is 'Internet'
[19-Oct-2017 08:33:35 UTC] DEBUG (7.1.7): Setting cookie WPO365_LOGIN_ERR_MSGS with value  set for  (https://[sitename].co.uk) OK 

I'm wondering if I've messed something up while playing around with this.  I might have a go at removing the plugin and my Azure app and starting completely from scratch going through your guide again (will probably have to be tomorrow before I get chance though)

**Comment by wpo365** [comment]
Hi @ALNSBroadside, I don't think you need to go through all that trouble. Looking at the Log File it seems the authentication flow is OK. However, the plugin sets a cookie with a value that is also sent along with the request to Microsoft and it seems this cookie is missing when the validation flow continues upon returning from logging in. What browser are you using?

**Comment by ALNSBroadside** [comment]
Using Chrome 61.0.3163.100 here!

Hmm, you've just given me a thought there - I'm stuck behind a proxy we don't control (the website is out on the internet though, not behind the proxy with us). I wonder if that could be stripping something out?

**Comment by wpo365** [comment]
Then it's me doing something terribly wrong when setting the cookie :) I will add some additional logging to verify that this is indeed the problem.

**Comment by wpo365** [comment]
@ALNSBroadside I have uploaded version 1.13 and changed how cookies are set (now almost identical to the way Wordpress is setting them) and added additional logging that would show whether or not the nonce cookie is found. Would be really great if you can give it another try!

**Comment by ALNSBroadside** [comment]
Ooh, that's got it!

I'm logged in as a subscriber and it's created the user and taken me to the user dashboard! Just tried with a second user too and yup it works!

Logs in case you want to see anything:
[19-Oct-2017 11:19:54 UTC] DEBUG (7.1.7): Checking whether user is O365 user -> Not logged on
[19-Oct-2017 11:19:54 UTC] DEBUG (7.1.7): Cancelling session validation for page index.php because selected scenario is 'Internet'
[19-Oct-2017 11:20:03 UTC] DEBUG (7.1.7): Processing incoming OpenID Connect id_token
[19-Oct-2017 11:20:03 UTC] DEBUG (7.1.7): Processing an new id token
[19-Oct-2017 11:20:03 UTC] DEBUG (7.1.7): Algorithm found RS256
[19-Oct-2017 11:20:03 UTC] DEBUG (7.1.7): Skipping SSL peer and host verification
[19-Oct-2017 11:20:03 UTC] DEBUG (7.1.7): Getting current public keys from MSFT
[19-Oct-2017 11:20:04 UTC] DEBUG (7.1.7): Found nonce cookie with value: 59e88a5ef2ef9
[19-Oct-2017 11:20:04 UTC] DEBUG (7.1.7): Setting cookie WPO365_NONCE with value 
[19-Oct-2017 11:20:04 UTC] DEBUG (7.1.7): found user with ID 5
[19-Oct-2017 11:20:04 UTC] DEBUG (7.1.7): Setting cookie WPO365_AUTH with value 1508415604;1508415609
[19-Oct-2017 11:20:04 UTC] DEBUG (7.1.7): Redirecting to https://[sitename].co.uk/wp-admin/

**Comment by wpo365** [comment]
@ALNSBroadside Fantastic! This was very valuable for me and for the plugin ... I guess I need to send you some wonderfully smelling Swiss Cheese to say thanks :) If it is OK for you then I will close this issue. But please feel free opening new issues if you'd like to request a new feature or if you uncover new untested areas. Ps, Did it take the user to his/her dashboard because you entered that as reply-URL?

**Comment by ALNSBroadside** [comment]
Haha not at all - I'm pretty sure I owe you one for sticking with it! Thank you very, very much and you have an awesome plugin :D

I think it took them there because I'd tried going to wp-admin, but as a subscriber they don't get the full thing, just the dashboard so when it tried to redirect to wp-admin it took me there.

Just confirmed actually - I set the default role to "Editor" and logged in with another account and it did take me to the wp-admin :)

Thank you again for your hard work on this!

**Comment by wpo365** [comment]
@ALNSBroadside In that case I'll keep the cheese in Switzerland. I guess it would have stirred some uproar at the border anyway :) 

Ps, Feel free to rate the plugin over at the WP plugin directory https://wordpress.org/plugins/wpo365-login/

**Comment by asoet** [comment]
Just installed the plugin and I have the same problem with the same logs:

Validating session for page index.php
[15-Feb-2018 09:54:48 UTC] DEBUG ( 5.6.33 ): Cannot look up user meta WPO365_AUTH for user that is not logged
[15-Feb-2018 09:54:48 UTC] DEBUG ( 5.6.33 ): Getting fresh id and authorization tokens: https://login.microsoftonline.com/[tenantname]/oauth2/authorize?client_id=[clientId]&response_type=id_token+code&redirect_uri=http%3A%2F%2F[siteName]%2F&response_mode=form_post&scope=openid&resource=00000002-0000-0000-c000-000000000000&state=https%3A%2F%2F[sitename]%2Fwp-admin%2F&nonce=1aa43a8192
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Processing incoming OpenID Connect id_token
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Processing an new id token
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Algorithm found RS256
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Skipping SSL peer and host verification
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Getting current public keys from MSFT
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Setting cookie WPO365_LOGIN_ERR_MSGS with value [Cookie]
[15-Feb-2018 09:54:49 UTC] ERROR ( 5.6.33 ): id token could not be processed and user will be redirected to default Wordpress login
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Destroying session index.php
[15-Feb-2018 09:54:49 UTC] DEBUG ( 5.6.33 ): Tried deleting user meta for WPO365_AUTH
[15-Feb-2018 09:54:50 UTC] DEBUG ( 5.6.33 ): Cancelling session validation for page wp-login.php because selected scenario is 'Internet'
[15-Feb-2018 09:54:50 UTC] DEBUG ( 5.6.33 ): Setting cookie WPO365_LOGIN_ERR_MSGS with value 
[15-Feb-2018 09:54:56 UTC] DEBUG ( 5.6.33 ): Cancelling session validation for page wp-login.php because selected scenario is 'Internet'
[15-Feb-2018 09:54:56 UTC] DEBUG ( 5.6.33 ): Cancelling session validation for page index.php because selected scenario is 'Internet'
